### ISSUE TITLE
Visual Studio does not build into the same folder the /res are copied

### ISSUE THREAD

**Issue by ManuelKugelmann** [bmwcarit/ramses#17]
Binaries end up in bin/Debug/ or bin/Release, while the resources are in /bin/res. This makes testing inconvenient, since the resources are not in the expected relative path to the binaries.  Afaik using cmake generator ressions like e.g.  RUNTIME_OUTPUT_DIRECTORY "$<1:${OUT_DIR}>" fixes the problem of Visual Studio building to subdirectories.

**Comment by ManuelKugelmann** [comment]
Just appending `$<0:>` to any output path will get rid of the unwanted Visual Studio sub-folders

**Comment by violinyanev** [comment]
Sorry for the long delay, will look into this. @ManuelKugelmann we are talking 'windows only' here, right? Other platforms don't have the option to build with multiple configurations at once (btw MS VS has bugs with this too).

**Comment by ManuelKugelmann** [comment]
yes, windows MSVC

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann 

we could not find a way to implement what you need without removing multi-platform builds. We also can't drop support for older CMake, and generator expressions are a rather modern feature which doesn't work reliably on all generators yet. Sorry, have to close this for now.
