### ISSUE TITLE
Registering own log appender

### ISSUE THREAD

**Issue by martin-hackenberg-paradoxcat** [bmwcarit/ramses#41]
When using ramses in the past it was possible to register a custom log appender with ::ramses_internal::GetRamsesLogger().addAppender(*logAppender_).

This is no longer possible in ramses 24 and the use of ramses_internal feature also wasn't optimal. For a controlled processing and filtering of logs in our client application an public API access to the ramses log messages is needed, equivalent to the former internal version.

**Comment by violinyanev** [comment]
Hello @martin-hackenberg-paradoxcat ! Understood. In order for us to provide the best possible implementation, can you give a bit of input:
- what kind of logs would you like to get? All logs over all log levels? Just selected log levels?
- do you need separation between client/renderer logs?
- do you "just want to intercept stdout/stderr" or do you want to do more complex things?
- do you want a copy of the logs, or also disable ramses logging?

Thanks!
Violin

**Comment by martin-hackenberg-paradoxcat** [comment]
Hello @violinyanev,
   
- what kind of logs would you like to get? All logs over all log levels? Just selected log levels?
Ramses (framework, client and renderer) is started as part of our application, thus we want to configure the log level accordingly on startup. Configurable log levels / contexts during runtime would be nice to have.

- do you need separation between client/renderer logs? / do you "just want to intercept stdout/stderr" or do you want to do more complex things?
We would like to be able to doe more complex things. For example filter the ramses logs based on context and log level. The context would also allow us to distinguish between framework, client and renderer logs.

- do you want a copy of the logs, or also disable ramses logging?
Nice to have. if we can replace the default ramses logger with our own logger.

Configuring of log levels on framework creation:
```
char const* argv[] = { "RamsesComposer.exe",
			"--log-level-contexts-filter", "trace:RAPI,off:RPER,debug:RRND,off:RFRA,off:RDSM,info:RCOM",
			"--log-level-console", "trace",
			"--log-level-dlt", "trace" };

ramses::RamsesFrameworkConfig config(sizeof(argv) / sizeof(argv[0]), argv );
config.setPeriodicLogsEnabled(false);
boost::shared_ptr<RamsesParameters const> ramsesParameters = boost::dynamic_pointer_cast<RamsesParameters const>(parameters);
ramsesParameters->apply(config);
ramework_ = new ramses::RamsesFramework(config);
```
We would also like to set the log context and level filtering via an API.
Previously we used ramses_internal to register the custom LogAppender like this:
```
class CustomLogAppender : public ramses_internal::LogAppenderBase {
public:
	virtual void log(const ramses_internal::LogMessage& logMessage) override {
		auto level = custom_log_system::translateLogLevelFromRamsesToOwn(logMessage.getLogLevel());
		custom_log_system::create_log(LOG_SRC_RAMSES, level, logMessage.getContext().getContextName()) << logMessage.getStream().c_str();
	}
};

void setupRamses()
{
	...
	logAppender_ = new RamsesLogAppender();
	logAppender_->setLogLevel(ramses_internal::ELogLevel::Trace);
	::ramses_internal::GetRamsesLogger().addAppender(*logAppender_);
};
```

Thanks
Martin

**Comment by ManuelKugelmann** [comment]
I had to hack around this, too:
```
m_callbackLogAppender = new CallbackLogAppender((ramses_internal::ELogLevel) logLevel, log);
// ramses_internal::GetRamsesLogger().addAppender(*m_callbackLogAppender );
auto appenderLock = &((&ramses_internal::GetRamsesLogger())->*get(m_appenderLock()));
std::unique_lock<std::mutex> lock(*appenderLock);
auto& logAppenders = ((&ramses_internal::GetRamsesLogger())->*get(m_logAppenders()));
logAppenders.push_back((ramses_internal::LogAppenderBase*)m_callbackLogAppender);
lock.unlock();
```

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann @martin-hackenberg-paradoxcat 

we added a custom logger to the official API as a static setter - can you check if it works for your purposes?
(added in 27.0.119, function name is RamsesFramework::SetLogHandler)
