### ISSUE TITLE
Bool Context_WGL::init() is not virtual  and overrides are final - forced to copy Context_WGL to extend it

### ISSUE THREAD

**Issue by ManuelKugelmann** [bmwcarit/ramses#55]
I have a custom Contex implementation that needs some initialization that is different from that in Bool Context_WGL::init(). Because it is not virtual, i had to copy the whole class and modify it instead of reusing most of the code.
This makes maintenance of my code more cumbersome than necessary.

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann would it be sufficient for you to just remove the 'final' or do you need to extend the class in other ways? Can you provide some code/example what you need?

**Comment by ManuelKugelmann** [comment]
Hi @violinyanev  - I think that would suffice, but I'll have a closer look. 
BTW: why not make every method that is not on a performance critical path `virtual` and non-`final` for easy extensibility?

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann ,

generally - for code readibility. 'final' is a signal for the code reader that this is the 'final class', no more subclasses. Those classes are not user-extensible, so we didn't consider it necessary to allow extension

**Comment by ManuelKugelmann** [comment]
@violinyanev I guess that depends on who you see as user and how you want to do extensions :) 
I did start with access to the ramses source, but opaque updating - sometimes I had to use a private non-OSS version, sometimes the OSS version. In situations like this I prefer to do additive-only extensions, treating the original source code like an external library and not modifying or touching it's source.

I think it would be beneficial to ramses's future to make the platform part of ramses extensible to allow adding new platforms or extending existing ones.

**Comment by violinyanev** [comment]
Yes, we had an internal discussion and we also see it this way. It's quite a lot of work though, so the "nice" solution is probably something further down the road. But I think we can just open the classes for modification for now to make it easier to do what you do without having to keep local patches.

Btw regarding the 'future argument', there is a reason we chose the MPL license for ramses. We would like to understand what is missing in the library and adapt it based on requirements from users. The MPL requires you to either use the code as-is, or add more files, or contribute partial modifications. By doing so we hope to learn from such modifications and make it easier to have them without forcing forks. But we can only do so if you contribute them ;)

**Comment by violinyanev** [comment]
Hi @ManuelKugelmann ,
in the latest release (27.0.115) we made most of the final classes in the platform domain open for modification (still virtual, but you can override them and e.g. call the base version of not - if you know what you are doing). Can you check if it works better for you now and close the tickets which are obsolete (and update the ones which still need work)?

Regards,
Violin
